### ISSUE TITLE
Batoto forums + follows + basic comic data has been migrated to vatoto.com

### ISSUE THREAD

**Issue by ZdrytchX** [fuzzykiller/batoto-grabber#2]
As the title says so this application will need to support the new vatoto.com based URLs.

The URL tree seems to be identicle to batoto's old URL system however chapter information on individual comic pages are missing.

I've made a mention in the discord server to get the old list of chapters up at least for the application to work but don't bet on it. For the mean time you could make it so the database won't include the chapter listings and its uploader account name, and the scanlator group listings would be shorter (if it takes the data from the raw /follows/ page at least).

**Comment by btzdnl** [comment]
Thanks for the suggestion. However, the intro page says not to scrape, so I’m not sure whether it would be appropriate to make the program compatible. The page is really slow to respond sometimes, so I’m inclined to agree with this rule.

**Comment by ZdrytchX** [comment]
Oh that intro page wasn't there before.
